apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "secret-watcher.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default (include "secret-watcher.fullname" .) }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "secret-watcher.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
