apiVersion: v2
name: secret-rotator
description: A Kubernetes secret rotation and monitoring system
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - secrets
  - security
  - rotation
# home: https://github.com/your-org/secret-rotator
# sources:
#   - https://github.com/your-org/secret-rotator
# maintainers:
#   - name: Your Name
#     email: your.email@example.com